version: '3.0'
services:
  db:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=booking"
    ports: 
      - "3306:3306"

  web:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "80:80"
    depends_on:
      - db