# Generated by Django 2.1.3 on 2019-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swingtime', '0002_auto_20190206_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=16)),
                ('occurrence', models.ManyToManyField(to='swingtime.Occurrence')),
            ],
        ),
    ]
